### ISSUE TITLE
Tests fail in *nix build

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/binskim#270]
- Need to special-case Windows-specific PDB parsing tests.
- 'UseCheckedFunctionsWithGCC' failures
- Functional tests not generating `BinSkim.win-x64.ni.dll.sarif`

**Comment by michaelcfanning** [comment]
```
[xUnit.net 00:00:04.9813150]     Microsoft.CodeAnalysis.IL.BuiltInRuleFunctionalTests.Driver_BuiltInRuleFunctionalTests [FAIL]
   System.IO.FileNotFoundException : Could not find file '/home/mikefan/src/binskim/src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/NonWindowsExpected/BinSkim.win-x64.ni.dll.sarif'.
]   at Microsoft.CodeAnalysis.IL.BuiltInRuleFunctionalTests.RunRules(StringBuilder sb, String inputFileName) in /home/mikefan/src/binskim/src/Test.FunctionalTests.BinSkim.Driver/BaselineTests.cs:line 122
 
[xUnit.net 00:00:01.8330362]     Microsoft.CodeAnalysis.IL.Rules.RuleTests.UseCheckedFunctionsWithGCC_Fail [FAIL]
  X Microsoft.CodeAnalysis.IL.Rules.RuleTests.UseCheckedFunctionsWithGCC_Fail [3ms]
  Error Message:
   Assert.True() Failure
     at Microsoft.CodeAnalysis.IL.Rules.RuleTests.Verify(BinarySkimmer skimmer, IEnumerable`1 additionalTestFiles, Boolean useDefaultPolicy, Boolean expectToPass) in /home/mikefan/src/binskim/src/Test.FunctionalTests.BinSkim.Rules/RuleTests.cs:line 54

[xUnit.net 00:00:02.9263060]     Microsoft.CodeAnalysis.IL.Rules.RuleTests.UseCheckedFunctionsWithGCC_Pass [FAIL]
  X Microsoft.CodeAnalysis.IL.Rules.RuleTests.UseCheckedFunctionsWithGCC_Pass [< 1ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at Microsoft.CodeAnalysis.IL.Rules.RuleTests.Verify(BinarySkimmer skimmer, IEnumerable`1 additionalTestFiles, Boolean useDefaultPolicy, Boolean expectToPass) in /home/mikefan/src/binskim/src/Test.FunctionalTests.BinSkim.Rules/RuleTests.cs:line 54

[xUnit.net 00:00:01.2054062]     Microsoft.CodeAnalysis.BinaryParsers.PEBinaryTests.PEBinary_PdbAvailable [FAIL]
  X Microsoft.CodeAnalysis.BinaryParsers.PEBinaryTests.PEBinary_CanCreateIDiaSourceFromMsdia [62ms]
  Error Message:
   Did not expect any exception, but found System.DllNotFoundException with message "Unable to load shared library 'msdia140.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libmsdia140.dll: cannot open shared object file: No such file or directory"
   at Microsoft.CodeAnalysis.BinaryParsers.PEBinaryTests.PEBinary_CanCreateIDiaSourceFromMsdia() in /home/mikefan/src/binskim/src/Test.UnitTests.BinaryParsers/PEBinary/PEBinaryTests.cs:line 70
  X Microsoft.CodeAnalysis.BinaryParsers.PEBinaryTests.PEBinary_PdbIsStripped [6ms]
  Error Message:
   Expected object not to be <null>.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.NotBeNull(String because, Object[] becauseArgs)
   at Microsoft.CodeAnalysis.BinaryParsers.PEBinaryTests.PEBinary_PdbIsStripped() in /home/mikefan/src/binskim/src/Test.UnitTests.BinaryParsers/PEBinary/PEBinaryTests.cs:line 61
  X Microsoft.CodeAnalysis.BinaryParsers.PEBinaryTests.PEBinary_PdbAvailable [1ms]
  Error Message:
   Expected object not to be <null>.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.NotBeNull(String because, Object[] becauseArgs)
   at Microsoft.CodeAnalysis.BinaryParsers.PEBinaryTests.PEBinary_PdbAvailable() in /home/mikefan/src/binskim/src/Test.UnitTests.BinaryParsers/PEBinary/PEBinaryTests.cs:line 36
```
