### ISSUE TITLE
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by chipitsine** [microsoft/binskim#479]
I run the todays master branch on linux (commit 1609a24472ff5ce3cc3bbd47f796542322a5d8a6).

```
./bld/bin/x64_Release/netcoreapp3.1/BinSkim analyze /home/ilia/haproxy/haproxy
```

exception is:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.SpanHelpers.IndexOf(Byte ByRef, Byte, Int32)
   at System.String.Ctor(SByte*)
   at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr)
   at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader.ReadString()
   at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader.ReadString(Int32)
   at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfCompilationUnit.ReadData(Microsoft.CodeAnalysis.BinaryParsers.Dwarf.IDwarfBinary, Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader, Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader, Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader, Microsoft.CodeAnalysis.BinaryParsers.Dwarf.NormalizeAddressDelegate)
   at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfCompilationUnit..ctor(Microsoft.CodeAnalysis.BinaryParsers.Dwarf.IDwarfBinary, Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader, Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader, Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader, Microsoft.CodeAnalysis.BinaryParsers.Dwarf.NormalizeAddressDelegate)
   at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfSymbolProvider.ParseOneCompilationUnitByOffset(Microsoft.CodeAnalysis.BinaryParsers.Dwarf.IDwarfBinary, Byte[], Byte[], Byte[], Microsoft.CodeAnalysis.BinaryParsers.Dwarf.NormalizeAddressDelegate, Int32)
   at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfSymbolProvider.ParseAllCompilationUnits(Microsoft.CodeAnalysis.BinaryParsers.Dwarf.IDwarfBinary, Byte[], Byte[], Byte[], Microsoft.CodeAnalysis.BinaryParsers.Dwarf.NormalizeAddressDelegate)
   at Microsoft.CodeAnalysis.BinaryParsers.ElfBinary..ctor(System.Uri, System.String)
   at Microsoft.CodeAnalysis.IL.Sdk.BinaryTargetManager.GetBinaryFromFile(System.Uri, System.String, System.String, Boolean)
   at Microsoft.CodeAnalysis.IL.Sdk.BinaryAnalyzerContext.get_Binary()
   at Microsoft.CodeAnalysis.IL.Sdk.BinaryAnalyzerContext.get_TargetLoadException()
   at Microsoft.CodeAnalysis.Sarif.Driver.AnalyzeCommandBase`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DetermineApplicabilityAndAnalyze(System.__Canon, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.Sarif.Driver.Skimmer`1<System.__Canon>>, System.__Canon, System.String, System.Collections.Generic.ISet`1<System.String>)

```

binary attached:

[haproxy.zip](https://github.com/microsoft/binskim/files/7111351/haproxy.zip)

**Comment by chipitsine** [comment]
if that's important, I ran on Fedora 35. "dotnet" packages installed from Fedora repo

**Comment by eddynaka** [comment]
@shaopeng-gh , can you verify if this error is still happening?

**Comment by shaopeng-gh** [comment]
able to repro this error,
worked on the fix and it is now merged in main.

(commit: https://github.com/microsoft/binskim/commit/3484d4686b7f0f4a4bbd956f22420c513d9496b9)
