### ISSUE TITLE
Abbreviated switches do not work

### ISSUE THREAD

**Issue by krwq** [Microsoft/binskim#64]
Repro:
```
BinSkim.exe analyze bin -p default -r -o binskim.report
```

Result:
```
Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CommandLine.Core.TypeLookup.FindTypeDescriptorAndSibling(String name, IEnumerable`1 specifications, StringComparer comparer)
   at CommandLine.Core.Switch.<>c__DisplayClass0_0.<Partition>b__0(Token t)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at CSharpx.EnumerableExtensions.Memorize[T](IEnumerable`1 source)
   at CommandLine.Core.TokenPartitioner.Partition(IEnumerable`1 tokens, Func`2 typeLookup)
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass0_0`1.<Build>b__7()
   at CommandLine.Core.InstanceChooser.MatchVerb(Func`3 tokenizer, IEnumerable`1 verbs, IEnumerable`1 arguments, StringComparer nameComparer, CultureInfo parsingCulture, IEnumerable`1 nonFatalErrors)
   at CommandLine.Core.InstanceChooser.<>c__DisplayClass0_0.<Choose>b__0()
   at CommandLine.Parser.ParseArguments(IEnumerable`1 args, Type[] types)
   at Microsoft.CodeAnalysis.IL.BinSkim.Main(String[] args)
```

(expanded version of them works)

**Comment by michaelcfanning** [comment]
The 'policy' command was recently changed to 'config', so use a -c below. Sorry for the inconvenience

BinSkim.exe analyze bin -**c** default -r -o binskim.report
