### ISSUE TITLE
Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_* Tests fail on a clean clone

### ISSUE THREAD

**Issue by dmachaj** [microsoft/binskim#666]
I just pulled the latest main and merged it into my branch.  I am now seeing test failures that were not there before.  I cloned a fresh copy of the repo and see the same failures there, so it is not related to my changes.

1. `git clone https://github.com/microsoft/binskim.git binskim2`
2. `cd binskim2`
3. `BuildAndTest.cmd`

Expected: The build and tests both succeed because this is a clean clone.
Actual: The following failures occur.

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.03]     Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_NotApplicable [FAIL]
  Failed Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_NotApplicable [14 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   534
  Stack Trace:
     at Microsoft.CodeAnalysis.IL.Rules.RuleTests.VerifyApplicabilityResults(BinarySkimmer skimmer, HashSet1 targets, Boolean useDefaultPolicy, AnalysisApplicability expectedApplicability, String ruleName, String expectedReasonForNotAnalyzing) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 377
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_NotApplicable() in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 1279
  Standard Output Messages:
 'BA2027:EnableSourceLink' - 'CanAnalyze' did not correctly indicate target applicability (unexpected return was 'ApplicableToSpecifiedTarget'): clangcl.pe.c.codeview.exe
 'BA2027:EnableSourceLink' - 'CanAnalyze' did not correctly indicate target applicability (unexpected return was 'ApplicableToSpecifiedTarget'): clangcl.pe.cpp.codeview.exe
 'BA2027:EnableSourceLink' - 'CanAnalyze' did not correctly indicate target applicability (unexpected return was 'ApplicableToSpecifiedTarget'): Native_x64_RustC_Rust_debuginfo2_v1.58.1.exe



[xUnit.net 00:00:01.29]     Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Pass [FAIL]
  Failed Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Pass [3 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   326
  Stack Trace:
     at Microsoft.CodeAnalysis.IL.Rules.RuleTests.Verify(BinarySkimmer skimmer, IEnumerable1 additionalTestFiles, Boolean useDefaultPolicy, Boolean expectToPass, Boolean bypassExtensionValidation) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 167
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.VerifyPass(BinarySkimmer skimmer, IEnumerable`1 additionalTestFiles, Boolean useDefaultPolicy, Boolean bypassExtensionValidation) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 34
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Pass() in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 1267
  Standard Output Messages:
 Expected 'BA2027:EnableSourceLink' success but saw no result at all for file: CPlusPlus_SourceLink.exe
 Expected 'BA2027:EnableSourceLink' success but saw no result at all for file: CSharp_FullPdb_SourceLink.dll
 Expected 'BA2027:EnableSourceLink' success but saw no result at all for file: CSharp_PortablePdb_SourceLink.dll



[xUnit.net 00:00:01.58]     Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Fail [FAIL]
  Failed Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Fail [2 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   106
  Stack Trace:
     at Microsoft.CodeAnalysis.IL.Rules.RuleTests.Verify(BinarySkimmer skimmer, IEnumerable1 additionalTestFiles, Boolean useDefaultPolicy, Boolean expectToPass, Boolean bypassExtensionValidation) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 167
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.VerifyFail(BinarySkimmer skimmer, IEnumerable`1 additionalTestFiles, Boolean useDefaultPolicy, Boolean bypassExtensionValidation) in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 43
   at Microsoft.CodeAnalysis.IL.Rules.RuleTests.BA2027_EnableSourceLink_Fail() in v:\T\binskim2\src\Test.FunctionalTests.BinSkim.Rules\RuleTests.cs:line 1273
  Standard Output Messages:
 Expected 'BA2027:EnableSourceLink' failure but saw no result at all for file: CPlusPlus_NoSourceLink.exe




Failed!  - Failed:     3, Passed:   102, Skipped:     0, Total:   105, Duration: 1 s - Test.FunctionalTests.BinSkim.Rules.dll (netcoreapp3.1)
BinSkim.Rules Functional tests execution FAILED.
Build and test did not complete successfully.
```

**Comment by dmachaj** [comment]
@pharring FYI

**Comment by dmachaj** [comment]
This appears to be blocking new changes.  The PR build for #667 is hitting the same test failures, which will block that change from being merged :(.

**Comment by pharring** [comment]
Thanks for tagging me and sorry about that. I thought all the tests passed on my PR, but it does look like the new SourceLink rule is at fault. Unfortunately, due to other commitments, I'm unable to look at this for a few days.
