### ISSUE TITLE
BinSkim cannot load config in json format correctly

### ISSUE THREAD

**Issue by eddynaka** [microsoft/binskim#688]
## What is the issue?

If you execute the command:
```
Binskim.exe analyze binskim.exe --config config.json
```

An exception will occur:
```
BINSKIM : error ERR998.ExceptionInInitialize : BA2006 : An exception was raised initializing check 'BuildWithSecureTools' (which has been disabled).
InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Sarif.PropertiesDictionary' to type 'System.String'.
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.TryGetProperty[T](String key, T& value)
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.GetProperty[T](PerLanguageOption`1 setting, Boolean cacheDefault)
   at Microsoft.CodeAnalysis.IL.Rules.BuildWithSecureTools.Initialize(BinaryAnalyzerContext context) in D:\a\r1\a\src\BinSkim.Rules\PERules\BA2006.BuildWithSecureTools.cs:line 90
   at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2.InitializeSkimmers(ISet`1 skimmers, TContext context)

C:\Tools\BinSkim.1.9.5\BinSkim.dll : error ERR998.ExceptionInAnalyze : BA2005 : An exception of type 'InvalidCastException' was raised analyzing 'BinSkim.dll' for check 'DoNotShipVulnerableBinaries' (which has been disabled). The exception may have resulted from a problem related to parsing the analysis target, and not specific to the rule, however.
InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Sarif.PropertiesDictionary' to type 'System.String'.
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.TryGetProperty[T](String key, T& value)
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.GetProperty[T](PerLanguageOption`1 setting, Boolean cacheDefault)
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.GetProperty[T](PerLanguageOption`1 setting)
   at Microsoft.CodeAnalysis.IL.Rules.DoNotShipVulnerableBinaries.Analyze(BinaryAnalyzerContext context) in D:\a\r1\a\src\BinSkim.Rules\PERules\BA2005.DoNotShipVulnerableBinaries.cs:line 90
   at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2.AnalyzeTargetHelper(TContext context, IEnumerable`1 skimmers, ISet`1 disabledSkimmers)
```

## How to reproduce?

1. Download the latest BinSkim package and unzip it.
2. Execute the command: `BinSkim.exe export-config config.json`
3. Execute the command: `BinSKim.exe analyze Binskim.exe --config config.json`
```
PS C:\Tools\BinSkim.1.9.5> .\binskim.exe analyze .\BinSkim.dll --config .\test.json
Analyzing...
BINSKIM : error ERR998.ExceptionInInitialize : BA2006 : An exception was raised initializing check 'BuildWithSecureTools' (which has been disabled).
InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Sarif.PropertiesDictionary' to type 'System.String'.
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.TryGetProperty[T](String key, T& value)
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.GetProperty[T](PerLanguageOption`1 setting, Boolean cacheDefault)
   at Microsoft.CodeAnalysis.IL.Rules.BuildWithSecureTools.Initialize(BinaryAnalyzerContext context) in D:\a\r1\a\src\BinSkim.Rules\PERules\BA2006.BuildWithSecureTools.cs:line 90
   at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2.InitializeSkimmers(ISet`1 skimmers, TContext context)

C:\Tools\BinSkim.1.9.5\BinSkim.dll : error ERR998.ExceptionInAnalyze : BA2005 : An exception of type 'InvalidCastException' was raised analyzing 'BinSkim.dll' for check 'DoNotShipVulnerableBinaries' (which has been disabled). The exception may have resulted from a problem related to parsing the analysis target, and not specific to the rule, however.
InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Sarif.PropertiesDictionary' to type 'System.String'.
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.TryGetProperty[T](String key, T& value)
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.GetProperty[T](PerLanguageOption`1 setting, Boolean cacheDefault)
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.GetProperty[T](PerLanguageOption`1 setting)
   at Microsoft.CodeAnalysis.IL.Rules.DoNotShipVulnerableBinaries.Analyze(BinaryAnalyzerContext context) in D:\a\r1\a\src\BinSkim.Rules\PERules\BA2005.DoNotShipVulnerableBinaries.cs:line 90
   at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2.AnalyzeTargetHelper(TContext context, IEnumerable`1 skimmers, ISet`1 disabledSkimmers)


Done. 1 files scanned.

One or more rules was disabled for an analysis target, as it was determined not to be applicable to it (this is a common condition). Pass --verbose on the command-line for more information.

Analysis did not complete due to one or more unrecoverable execution conditions.
Unexpected fatal runtime condition(s) observed: ExceptionInSkimmerInitialize, ExceptionInSkimmerAnalyze
```

## What should be the behavior?

It should have the same behavior as when you export a XML file and use it. Below are the commands:
1. Download the latest BinSkim package and unzip it.
2. Execute the command: `BinSkim.exe export-config config.xml`
3. Execute the command: `BinSKim.exe analyze Binskim.exe --config config.xml`
```
PS C:\Tools\BinSkim.1.9.5> .\binskim.exe analyze .\BinSkim.dll --config .\test.xml
Analyzing...

Done. 1 files scanned.
Analysis completed successfully.

One or more rules was disabled for an analysis target, as it was determined not to be applicable to it (this is a common condition). Pass --verbose on the command-line for more information.
```

**Comment by michaelcfanning** [comment]
This is a low-level SARIF SDK/Driver framework fix, BinSkim doesn't own this serialization logic. If you want to file an issue there.
