### ISSUE TITLE
`export-config` generated config have issue for BA2006

### ISSUE THREAD

**Issue by shaopeng-gh** [microsoft/binskim#751]
Repo steps:
1. export-config C:\Task\BinSkim\User\dwarf5\config.json
2. no changes to the exported file
3. analyze C:\Task\BinSkim\User\dwarf5\drop_linux_stage_linux_jobd\binskim\Binaries\akvvm_test --config C:\Task\BinSkim\User\dwarf5\config.json

Result:

```
Analyzing...
C:\GH\binskim\src\sarif-sdk\src\Sarif\PropertiesDictionary.cs : error ERR998.ExceptionInInitialize : BA2006 : An exception was raised initializing check 'BuildWithSecureTools' (which has been disabled).
InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.Sarif.PropertiesDictionary' to type 'System.String'.
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.TryGetProperty[T](String key, T& value) in C:\GH\binskim\src\sarif-sdk\src\Sarif\PropertiesDictionary.cs:line 112
   at Microsoft.CodeAnalysis.Sarif.PropertiesDictionary.GetProperty[T](PerLanguageOption`1 setting, Boolean cacheDefault) in C:\GH\binskim\src\sarif-sdk\src\Sarif\PropertiesDictionary.cs:line 54
   at Microsoft.CodeAnalysis.IL.Rules.BuildWithSecureTools.Initialize(BinaryAnalyzerContext context) in C:\GH\binskim\src\BinSkim.Rules\PERules\BA2006.BuildWithSecureTools.cs:line 74
   at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2.InitializeSkimmers(ISet`1 skimmers, TContext context) in C:\GH\binskim\src\sarif-sdk\src\Sarif.Driver\Sdk\MultithreadedAnalyzeCommandBase.cs:line 1063

C:\Task\BinSkim\User\dwarf5\drop_linux_stage_linux_jobd\binskim\Binaries\akvvm_test : error ERR997.ExceptionLoadingAnalysisTarget : Could not load analysis target 'akvvm_test'.

Done. 1 files scanned.

Analysis did not complete due to one or more unrecoverable execution conditions.
Unexpected fatal runtime condition(s) observed: ExceptionInSkimmerInitialize, ExceptionLoadingTargetFile
```

**Comment by michaelcfanning** [comment]
This is currently by design. The JSON configuration does not work. The issue is that we never designed a mechanism to reference type information (which are rendered in XML as attribute data.

Export your config as XML and it should work. Moving forward, we would actually use a SARIF file for configuration, rather than our custom JSON (using default rule enabled configuration etc).

**Comment by shaopeng-gh** [comment]
@suvamM @LingZhou-gh 
fyi above input from Michael.
